services:
  api:
    build: backend
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock  # Allow this container to administrate other containers
    ports:
      - "8000:8000"
